// <auto-generated />
namespace SisAdot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fk_tabela_ficha_animal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_tabela_ficha_animal));
        
        string IMigrationMetadata.Id
        {
            get { return "202010261256199_fk_tabela_ficha_animal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
