// <auto-generated />
namespace SisAdot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_usuarioID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_usuarioID));
        
        string IMigrationMetadata.Id
        {
            get { return "202010261110333_FK_usuarioID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
